apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  labels:
    app: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
    nodePort: 32123
